app = 'gnr-bold-leaf-1886'
primary_region = 'lax'

[build]
  [build.args]
    GO_VERSION = '1.21.0'

[env]
  PORT = '8080'
  discovery.type = "single-node"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 9200
  protocol = "tcp"
  force_https = true

[[services.ports]]
  handlers = ["http"]
  port = "443"

[[services.ports]]
  handlers = ["tls", "http"]
  port = "80"


[[services]]
  internal_port = 5601
  protocol = "tcp"
  force_https = true

[[services.ports]]
  handlers = ["http"]
  port = "5601"

[[services.tcp_checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  restart_limit = 0

[[mounts]]
  source = 'data'
  destination = '/Users/aa'

[[mounts]]
  source = "elasticsearch_data"
  destination = "/usr/share/elasticsearch/data"
