app = 'gnr-bold-leaf-1886'
primary_region = 'lax'

[build]
  [build.args]
    GO_VERSION = '1.21.0'

[[services]]
  internal_port = 3001
  protocol = "tcp"
  [[services.ports]]
    port = 3001
    handlers = ["http"]

[[services]]
  internal_port = 5601
  protocol = "tcp"
  [[services.ports]]
    port = 5601
    handlers = ["http"]

[[services]]
  internal_port = 9200
  protocol = "tcp"
  [[services.ports]]
    port = 9200
    handlers = ["http"]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[env]
  PORT = '8080'
  discovery.type = "single-node"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'data'
  destination = '/Users/aa'

